# BEGIN_KITTY_THEME
# Gruvbox Dark Soft
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12
# END_KITTY_FONTS

# kitty perf from https://sw.kovidgoyal.net/kitty/performance/#keyboard-to-screen-latency
input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

enable_audio_bell no
