# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/
# Credit to https://github.com/LilAiluropoda/hyprland-gruvbox-theme for most config

#################
### AUTOSTART ###
#################

# TODO: Notification daemon
# exec-once = dunst
# TODO: Authentication agent
# exec-once = /usr/lib/polkit-kde-authentication-agent-1 
exec-once = waybar & hyprpaper & hyprsunset
# TODO: needed? Fix for Screen Sharing 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Env/Alias settings
source = ~/.config/hypr/modules/env.conf
# Monitor settings
source = ~/.config/hypr/modules/monitors.conf
# General/Appearance settings
source = ~/.config/hypr/modules/general.conf
# Input/Device settings
source = ~/.config/hypr/modules/input.conf
# Rule settings
source = ~/.config/hypr/modules/rules.conf
# Keybinds settings
source = ~/.config/hypr/modules/binds.conf

###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
